language: node_js

node_js:
  - "0.12"
  - "5"
  - "6"
  - "6.1"
  - "stable"

sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
    - postgresql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm test
